language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t react-test .

script:
    - docker run -e CI=true react-test npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-638169379665"
    bucket_path: "docker-react"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
